spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: ${CAMUNDA_DB_USERNAME}
    password: ${CAMUNDA_DB_PASSWORD}
    #url: jdbc:h2:mem:camunda-spring-boot;DB_CLOSE_ON_EXIT=true

camunda.bpm:
  job-execution.deployment-aware: true

zuul:
  endpoints.routes.enabled: false
  routes:
    async_deployment:
      path: /async_deployment/**
      url: http://localhost:8090/forms


